services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://hushline:hushline@postgres:5432/hushline
      - FLASK_ENV=development
      - ADMIN_INPUT_SOURCE="environment"
      - ADMIN_SECRET="bi5FDwhZGKfc4urLJ_ChGtIAaOPgxd3RDOhnvct10mw="
      - REGISTRATION_CODES_REQUIRED=false
    volumes:
      - ./volumes/app:/data
      - ./:/app
    depends_on:
      - postgres

  postgres:
    image: "postgres:alpine"
    environment:
      - POSTGRES_USER=hushline
      - POSTGRES_PASSWORD=hushline
      - POSTGRES_DB=hushline
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data