---
services:
  app: &app_env
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 127.0.0.1:8080:8080
    environment:
      FLASK_APP: hushline
      FLASK_ENV: development
      ENCRYPTION_KEY: bi5FDwhZGKfc4urLJ_ChGtIAaOPgxd3RDOhnvct10mw=
      SECRET_KEY: cb3f4afde364bfb3956b97ca22ef4d2b593d9d980a4330686267cabcd2c0befd
      SQLALCHEMY_DATABASE_URI: postgresql://hushline:hushline@postgres:5432/hushline
      REGISTRATION_CODES_REQUIRED: 'false'
      ALIAS_MODE: always
      SESSION_COOKIE_NAME: session
      NOTIFICATIONS_ADDRESS: notifications@hushline.app
      DIRECTORY_VERIFIED_TAB_ENABLED: "${DIRECTORY_VERIFIED_TAB_ENABLED:-true}"
      SMTP_FORWARDING_MESSAGE_HTML: |
        âœŠ Email forwarding is powered by
        <a href="https://riseup.net" target="_blank">Riseup.net</a>.
      BLOB_STORAGE_PRIVATE_DRIVER: file-system
      BLOB_STORAGE_PRIVATE_FS_ROOT: /tmp/blob-storage/private
    volumes:
      - ./:/app
    depends_on:
      - dev_data
    restart: always

  dev_data:
    <<: *app_env
    ports: []
    restart: on-failure
    command: make dev-data
    depends_on:
      - postgres

  postgres:
    image: postgres:16.4-alpine3.20
    environment:
      POSTGRES_USER: hushline
      POSTGRES_PASSWORD: hushline
      POSTGRES_DB: hushline
    ports:
      - 127.0.0.1:5432:5432
